import LocalizedStrings from 'react-localization'

export const languagesList = {
  en: 'English',
  fr: 'Français',
}

export let strings = new LocalizedStrings({
  en: {
    routes: {
      wildAdventures: 'Wild Adventures',
      categories: 'Categories',
      adventures: 'Adventures',
      account: 'Account',
      register: 'Register',
      logout: 'Logout',
      login: 'Login',
      home: 'Home',
      notMatch: 'This page does not exist.',
    },
    home: {
      welcomeText:
        'Wild Aventures wish you welcome, find the categories of adventures in the spotlight as well as our most popular adventures.',
      adventureTitle: 'Adventures in the spotlight',
      categoryTitle: 'Categories in the spotlight',
    },
    adventures: {
      location: 'Location',
      categoriesListAdventure: 'Categories list of the adventure',
      from: 'From',
      to: 'To',
      price: 'Price',
      action: 'Action',
      reserve: 'Reserve',
      removeFromCart: 'Remove from cart',
      toReserve: 'To reserve',
      register: 'register',
      or: 'or',
      logIn: 'log in',
      reserveAdventure: 'Reserve this adventure',
      noSessions: 'No scheduled session for this adventure',
    },
    categories: {
      categoriesList: 'Categories list',
      goAdventure: 'Go on an adventure',
      adventuresList: 'Adventures list',
    },
    comments: {
      commentsList: 'Comments',
      said: 'said',
      reply: 'Reply',
      cancel: 'Cancel',
      send: 'Send',
      form: {
        contentMessageRule: 'Thank you to enter a comment.',
        contentPlaceholder: 'Write your comment here',
      },
    },
    user: {
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password',
      logIn: 'Log in',
      or: 'Or',
      registerNow: 'register now!',
      register: 'Register',
      upload: 'Upload',
      send: 'Send',
      deactivateAccount: 'Deactivate my account',
      form: {
        emailLabel: 'E-mail',
        usernameValidEmail: 'The input is not valid e-mail!',
        usernameMessageRule: 'Please input your e-mail!',
        usernamePlaceholder: 'E-mail',
        currentEmailLabel: 'Current e-mail',
        newEmailLabel: 'New e-mail',
        passwordLabel: 'Password',
        currentPasswordLabel: 'Current password',
        passwordMessageRule: 'Please input your password!',
        passwordPlaceholder: 'Password',
        confirmPasswordLabel: 'Confirm password',
        confirmPasswordMessageRule: 'Please confirm your password!',
        newPasswordLabel: 'New password',
        newPasswordMessageRule: 'Please input your new password!',
        confirmNewPasswordLabel: 'Confirm new password',
        confirmNewPasswordMessageRule: 'Please confirm your new password!',
        compareToFirstPassword: 'Two passwords that you enter is inconsistent!',
        avatarLabel: 'Avatar',
        pseudoLabel: 'Pseudo',
        newPseudoLabel: 'New pseudo',
        currentPseudoLabel: 'Current pseudo',
        pseudoTooltipTitle: 'What do you want others to call you?',
        pseudoMessageRule: 'Please input your nickname!',
        firstnameLabel: 'Firstname',
        firstnameMessageRule: 'Please input your firstname!',
        lastnameLabel: 'Lastname',
        lastnameMessageRule: 'Please input your lastname!',
        addressLabel: 'Address',
        addressMessageRule: 'Please input your address!',
        postalCodeLabel: 'Postal code',
        postalCodeMessageRule: 'Please input your postal code!',
        cityLabel: 'City',
        cityMessageRule: 'Please input your city!',
        countryLabel: 'Country',
        countryMessageRule: 'Please input your country!',
        phoneNumberLabel: 'Phone number',
        phoneNumberMessageRule: 'Please input your phone number!',
        birthDateLabel: 'Birth date',
        birthDateMessageRule: 'Please input your birth date!',
        birthDatePlaceholder: 'Select date',
        birthDateFormat: 'DD/MM/YYYY',
      },
    },
    orders: {
      peopleAdventure: 'Number of people participating in the adventure.',
      totalSession: 'Total for this session',
      remove: 'Remove',
      orderUpdateRequest: 'Request for update of order',
      orderUpdateDate: 'Update of the order of the',
      orderCancellationRequest: 'Request for cancellation of order',
      orderCancellationDate: 'Cancellation of the order of the',
      orderCancellation: 'Cancel my order',
      orderModify: 'Modify my order',
      pay: 'Pay',
      cancel: 'Cancel',
      edit: 'Edit',
      requestDeletionTreatment: 'Request for deletion during treatment.',
      requestUpdateProcessed: 'Request to update the order being processed.',
      noActionAvailable: 'No action available.',
      unpaid: 'Unpaid.',
      finalized: 'Finalized.',
      deletionRequest: 'Request for deletion.',
      updateRequest: 'Request for update.',
      unrecognizedStatus: 'Unrecognized status.',
      orderDate: 'Order date',
      status: 'Status',
      action: 'Action',
      ordersList: 'My orders list',
      emptyOrdersList: 'You have not made any orders.',
      makeOrder: 'Make your order',
      from: 'from',
      to: 'to',
      total: 'Total',
      continueOrder: 'Continue my order',
      noSessionsCart: 'No sessions have been added to the cart.',
      adventure: 'Adventure',
      numberParticipants: 'Number of participants',
      totalEuro: 'Total in euros',
      suppression: 'Suppression',
      orderSummary: 'Order summary',
      form: {
        messageMessageRule: 'Please input a message for administrators.',
        messagePlaceholder: 'Write your message for administrators.',
      },
    },
    statusCode: {
      wrongCredentials: 'Wrong credentials.',
      accountCreation: 'Problem when creating the account. Please try again.',
      userInformations:
        'Problem when retrieving user information. Please try again.',
      userUpdate: 'Problem while updating the user. Please try again.',
      userAvatar: 'Problem while recovering the user avatar. Please try again.',
      userAvatarUpdate:
        'Problem when updating the user avatar. Please try again.',
      serverNotFound: 'Problems accessing the server. Please, try again later.',
      commentAdd: 'Problem when adding the comment. Please try again.',
      commentUpdate: 'Problem when updating the comment. Please try again.',
      orderChargeError: 'Problem loading payment form. Please try again.',
      creatingOrderError: 'Problem when creating the order. Please try again.',
      creatingDemandError:
        'Problem when creating the demand. Please try again.',
      sessionUpdateError:
        'Problem when updating the session. Please try again.',
      getOrderError: 'Problem when getting the order. Please try again.',
      orderLength: 'Your order must at least contain an adventure.',
      gettingAdventureError: 'Error getting the adventure.',
      gettingSessionError: 'Error getting the session.',
      paymentError: 'Problem during payment. Please try again.',
    },
  },
  fr: {
    routes: {
      wildAdventures: 'Wild Adventures',
      categories: 'Catégories',
      adventures: 'Aventures',
      account: 'Compte',
      register: 'Inscription',
      logout: 'Déconnexion',
      login: 'Connexion',
      home: 'Accueil',
      notMatch: "Cette page n'existe pas.",
    },
    home: {
      welcomeText:
        "Wild Aventures vous souhaite la bienvenue, retrouvez les catégories d'aventures à l'honneur ainsi que nos aventures les plus populaires.",
      adventureTitle: "Les aventures à l'honneur",
      categoryTitle: "Les catégories à l'honneur",
    },
    adventures: {
      location: 'Localisation',
      categoriesListAdventure: "Liste des catégories de l'aventure",
      from: 'Du',
      to: 'Au',
      price: 'Prix',
      action: 'Action',
      reserve: 'Réserver',
      removeFromCart: 'Supprimer du panier',
      toReserve: 'Pour réserver',
      register: "s'inscrire",
      or: 'ou',
      logIn: 'se connecter',
      reserveAdventure: 'Réserver cette aventure',
      noSessions: 'Aucune session de programmée pour cette aventure',
    },
    categories: {
      categoriesList: 'Liste des catégories',
      goAdventure: "Partez à l'aventure",
      adventuresList: 'Liste des aventures',
    },
    comments: {
      commentsList: 'Commentaires',
      said: 'a dit',
      reply: 'Répondre',
      cancel: 'Annuler',
      send: 'Envoyer',
      form: {
        contentMessageRule: 'Merci de rentrer un commentaire.',
        contentPlaceholder: 'Écrivez votre commentaire ici',
      },
    },
    user: {
      rememberMe: 'Se rappeler de moi',
      forgotPassword: 'Mot de passe oublié',
      logIn: 'Se connecter',
      or: 'Ou',
      registerNow: 'se créer un compte !',
      register: "S'inscrire",
      upload: 'Uploader',
      send: 'Envoyer',
      deactivateAccount: 'Désactiver mon compte',
      form: {
        emailLabel: 'Email',
        usernameValidEmail: "Ce n'est pas un email valide !",
        usernameMessageRule: 'Merci de renseigner votre email !',
        usernamePlaceholder: 'Email',
        currentEmailLabel: 'Adresse email actuelle',
        newEmailLabel: 'Nouvelle adresse email',
        passwordLabel: 'Mot de passe',
        currentPasswordLabel: 'Mot de passe actuel',
        passwordMessageRule: 'Merci de renseigner votre mot de passe !',
        passwordPlaceholder: 'Mot de passe',
        confirmPasswordLabel: 'Confirmation du mot de passe',
        confirmPasswordMessageRule: 'Merci de confirmer votre mot de passe !',
        newPasswordLabel: 'Nouveau mot de passe',
        newPasswordMessageRule:
          'Merci de renseigner votre nouveau mot de passe !',
        confirmNewPasswordLabel: 'Confirmation',
        confirmNewPasswordMessageRule:
          'Merci de confirmer votre nouveau mot de passe !',
        compareToFirstPassword: 'Les deux mots de passe ne correspondent pas !',
        avatarLabel: 'Avatar',
        pseudoLabel: 'Pseudo',
        newPseudoLabel: 'Nouveau pseudo',
        currentPseudoLabel: 'Pseudo actuel',
        pseudoTooltipTitle: 'Comment souhaitez-vous être appelé ?',
        pseudoMessageRule: 'Merci de renseigner votre pseudo !',
        firstnameLabel: 'Prénom',
        firstnameMessageRule: 'Merci de renseigner votre prénom !',
        lastnameLabel: 'Nom',
        lastnameMessageRule: 'Merci de renseigner votre nom !',
        addressLabel: 'Adresse',
        addressMessageRule: 'Merci de renseigner votre adresse !',
        postalCodeLabel: 'Code postal',
        postalCodeMessageRule: 'Merci de renseigner votre code postal !',
        cityLabel: 'Ville',
        cityMessageRule: 'Merci de renseigner votre ville !',
        countryLabel: 'Pays',
        countryMessageRule: 'Merci de renseigner votre pays !',
        phoneNumberLabel: 'Numéro de téléphone',
        phoneNumberMessageRule:
          'Merci de renseigner votre numéro de téléphone !',
        birthDateLabel: 'Date de naissance',
        birthDateMessageRule: 'Merci de renseigner votre date de naissance !',
        birthDatePlaceholder: 'Sélectionner une date',
        birthDateFormat: 'DD/MM/YYYY',
      },
    },
    orders: {
      peopleAdventure: "Nombre de Personnes participants à l'aventure.",
      totalSession: 'Total pour cette session',
      remove: 'Supprimer',
      orderUpdateRequest: 'Demande de mise à jour de commande',
      orderUpdateDate: 'Mise à jour de la commande du',
      orderCancellationRequest: "Demande d'annulation de commande",
      orderCancellationDate: 'Annulation de la commande du',
      orderCancellation: 'Annuler ma commande',
      orderModify: 'Modifier ma commande',
      pay: 'Payer',
      cancel: 'Annuler',
      edit: 'Modifier',
      requestDeletionTreatment:
        'Demande de suppression en cours de traitement.',
      requestUpdateProcessed:
        'Demande de mise à jour de la commande en cours de traitement.',
      noActionAvailable: 'Aucune action disponible.',
      unpaid: 'Non Payée.',
      finalized: 'Finalisée.',
      deletionRequest: 'Demande de suppression.',
      updateRequest: 'Demande de mise à jour.',
      unrecognizedStatus: 'Statut non reconnu.',
      orderDate: 'Date de commande',
      status: 'Statut',
      action: 'Action',
      ordersList: 'Liste de mes commandes',
      emptyOrdersList: "Vous n'avez réalisé aucune commande.",
      makeOrder: 'Réaliser votre commande',
      from: 'du',
      to: 'au',
      total: 'Total',
      continueOrder: 'Poursuivre ma commande',
      noSessionsCart: "Aucune session n'a été ajouté au panier.",
      adventure: 'Aventure',
      numberParticipants: 'Nombre de participant',
      totalEuro: 'Total en euros',
      suppression: 'Suppression',
      orderSummary: 'Récapitulatif de commande',
      form: {
        messageMessageRule:
          'Merci de rentrer un message pour les administrateurs',
        messagePlaceholder: 'Écrivez votre message pour les administrateurs',
      },
    },
    statusCode: {
      wrongCredentials: 'Identifiants invalides.',
      accountCreation:
        'Problème lors de la création du compte. Merci de réessayer.',
      userInformations:
        'Problème lors de la récupération des informations utilisateur.',
      userUpdate:
        "Problème lors de la mise à jour de l'utilisateur. Merci de réessayer.",
      userAvatar:
        "Problème lors de la récupération de l'avatar utilisateur. Merci de réessayer.",
      userAvatarUpdate:
        "Problème lors de la mise à jour de l'avatar utilisateur. Merci de réessayer.",
      serverNotFound:
        "Problèmes d'accès au serveur. Merci de réessayer plus tard.",
      commentAdd:
        "Problème lors de l'ajout du commentaire. Merci de réessayer.",
      commentUpdate:
        'Problème lors de la mise à jour du commentaire. Merci de réessayer.',
      orderChargeError:
        'Problème lors du chargement de formulaire de paiement.',
      creatingOrderError:
        'Problème lors de la création de la commande. Merci de réessayer.',
      creatingDemandError:
        'Problème lors de la création de la demande. Merci de réessayer.',
      sessionUpdateError:
        'Problème lors de la mise à jour de la session. Merci de réessayer.',
      getOrderError:
        "Problème lors de l'obtention de la commande. Merci de réessayer.",
      orderLength: 'Votre commande doit au moins contenir une aventure.',
      gettingAdventureError: "Erreur lors de l'obtention de l'aventure.",
      gettingSessionError: "Erreur lors de l'obtention de la session.",
      paymentError: 'Problème lors du paiement. Merci de réessayer.',
    },
  },
})
