version: '3.1'
services:
  database:
    image: postgres:10.5-alpine
    container_name: wa_database
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/
      #- ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=wild_adventures
      - POSTGRES_USER=admin_wa
      - POSTGRES_PASSWORD=Shangri_La